version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      # install latest nodejs
      # - n latest
      - echo List directory files...
      - ls
      - echo Installing yarn...
      - npm install yarn --force
      - echo Installing source yarn dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist/ s3://connect-fe-host-dev/
      - aws cloudfront create-invalidation --distribution-id=${CLOUD_FRONT_ID} --paths '/*'
artifacts:
  files:
    - '**/*'