export const STEP = {
  CHECK_INVALID_CARD: 1,
  CHECK_BRANCH_Y_CUSTOMER: 2,
  CHECK_MONEY_SHORTAGE: 3,
  CHECK_NISA_WAKU: 4,
  CHECK_KANA_NAME: 5,
  CREATE_AUTH_SALE: 6,
  IMPORT_AUTH_SALE: 7,
  SNR_FUNDS: 8,
  SNR_DEPOSIT: 9,
  SNR_PAYMENT: 10,
};
